# Generated by Django 4.0.4 on 2022-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='evuser',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
