# Generated by Django 4.0.4 on 2022-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evuser', '0002_alter_evuser_options_evuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='evuser',
            name='address',
            field=models.CharField(default='HigsTower', max_length=64, verbose_name='주소'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evuser',
            name='category',
            field=models.CharField(default='개인', max_length=64, verbose_name='회원구분'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evuser',
            name='name',
            field=models.CharField(default='지알이시스템', max_length=64, verbose_name='회원이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evuser',
            name='phone',
            field=models.CharField(default='010-1234-5678', max_length=64, verbose_name='전화번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evuser',
            name='status',
            field=models.CharField(default='정상', max_length=64, verbose_name='회원상태'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evuser',
            name='usernumber',
            field=models.CharField(default='1010010112345678', max_length=64, verbose_name='회원번호'),
            preserve_default=False,
        ),
    ]
