# Generated by Django 4.0.4 on 2022-05-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evuser', '0004_alter_evuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evuser',
            name='category',
            field=models.CharField(choices=[('NORMAL', '일반'), ('GROUPED', '법인'), ('ETC', '기타')], default='NORMAL', max_length=64, verbose_name='회원구분'),
        ),
        migrations.AlterField(
            model_name='evuser',
            name='status',
            field=models.CharField(choices=[('CONTRACTED', '정상'), ('NOT_CONTRACTED', '해지'), ('STOPED', '유예')], default='CONTRACTED', max_length=64, verbose_name='회원상태'),
        ),
    ]
