# Generated by Django 4.0.4 on 2022-05-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evuser', '0004_alter_evuser_address'),
        ('charginginfo', '0004_remove_charginginfo_cpnumber_charginginfo_cpname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charginginfo',
            name='chargedname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evuser.evuser', verbose_name='사용자명'),
        ),
    ]
