# Generated by Django 4.0.4 on 2022-05-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charginginfo', '0005_alter_charginginfo_chargedname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charginginfo',
            options={'verbose_name': '충전정보', 'verbose_name_plural': '충전정보'},
        ),
    ]
